#!/usr/bin/env bash
set -euo pipefail

SERVICE="llama-server.service"
CURRENT_ENV="$HOME/.config/llama-server/current.env"
label="AI"

if [[ -f "$CURRENT_ENV" ]]; then
  # This file is generated by ai-model-picker.sh with safe quoted values.
  # shellcheck disable=SC1090
  source "$CURRENT_ENV"
  label="${AI_MODEL_LABEL:-AI}"
fi

if systemctl --user is-active --quiet "$SERVICE"; then
  state="ON"
  class="ai-on"
else
  state="OFF"
  class="ai-off"
fi

python3 - "$label" "$state" "$class" <<'PY'
import json, sys
label, state, klass = sys.argv[1], sys.argv[2], sys.argv[3]
short = label
short = short.replace('Google ', '').replace('GGUF', '').strip()
text = f"🤖 {short} {state}"
tooltip = f"AI backend: {state}\nModel: {label}\nClick: choose model\nRight-click: start/stop\nMiddle-click: restart"
print(json.dumps({"text": text, "tooltip": tooltip, "class": klass}))
PY
